/* ═══════════════════════════════════════════════════════════
   Dev Tools — Tool Registry
   Single source of truth for all tools.
   Used by nav.js (navigation) and index.html (tool cards).
   hrefs are bare filenames (no path prefix).
   ═══════════════════════════════════════════════════════════ */

const TOOLS = [
  {
    href:   'csv-to-insert.html',
    label:  'CSV → INSERT',
    icon:   'CSV',
    title:  'CSV → INSERT SQL',
    desc:   'CSV 파일을 업로드하거나 붙여넣으면 INSERT SQL 쿼리를 자동 생성합니다. 드래그 앤 드롭, 구분자 자동 감지(콤마·세미콜론·탭), Bulk/Individual 모드 지원.',
    tags:   ['MySQL', 'Oracle', 'PostgreSQL', 'Drag & Drop'],
    footer: 'CSV → INSERT SQL · Auto-detect delimiter',
  },
  {
    href:   'ddl-crud.html',
    label:  'DDL → CRUD',
    icon:   'SQL',
    title:  'DDL → CRUD Generator',
    desc:   'CREATE TABLE DDL을 입력하면 INSERT, SELECT, UPDATE, DELETE 쿼리를 자동 생성합니다. PK 자동 감지, MyBatis XML 지원.',
    tags:   ['MySQL', 'Oracle', 'PostgreSQL', 'MyBatis'],
    footer: 'DDL → INSERT · SELECT · UPDATE · DELETE',
  },
  {
    href:   'md-to-insert.html',
    label:  'MD → INSERT',
    icon:   'MD',
    title:  'Markdown → INSERT SQL',
    desc:   '마크다운 테이블 형식을 INSERT SQL 쿼리로 변환합니다. 숫자·불리언·NULL 타입 자동 감지, Individual / Bulk 모드 선택 지원.',
    tags:   ['MySQL', 'Oracle', 'PostgreSQL', 'Bulk INSERT'],
    footer: 'Markdown Table → INSERT',
  },
  {
    href:   'img-to-hex.html',
    label:  'IMG → HEX',
    icon:   'HEX',
    title:  'Image → Hex Converter',
    desc:   '이미지 파일을 Hex Dump, C Array, Python bytes, Base64 형식으로 변환합니다. 드래그 앤 드롭 지원.',
    tags:   ['Hex Dump', 'C Array', 'Python', 'Base64'],
    footer: 'Image → Hex Dump · C Array · Python · Base64',
  },
  {
    href:   'diff-viewer.html',
    label:  'Diff Viewer',
    icon:   'DIFF',
    title:  'Text / Code Diff Viewer',
    desc:   '두 텍스트 또는 JSON을 비교하여 변경된 부분을 한눈에 확인합니다. 추가·삭제·수정 라인 하이라이트와 unified patch 복사를 지원합니다.',
    tags:   ['Line Diff', 'JSON Diff', 'Patch Copy', 'Unified View'],
    footer: 'Original vs Modified — diff + patch',
  },
  {
    href:   'sql-erd.html',
    label:  'SQL → ERD',
    icon:   'ERD',
    title:  'SQL → ERD Viewer',
    desc:   'SQL DDL 파일을 업로드하거나 붙여넣으면 테이블 관계도(ERD)를 자동으로 그려줍니다. FK 관계·PK·컬럼 타입 시각화, 드래그 배치, SVG 내보내기 지원.',
    tags:   ['ERD', 'FK Relations', 'Schema Viz', 'SVG Export'],
    footer: 'DDL → Entity Relationship Diagram',
  },
  {
    href:   'json-formatter.html',
    label:  'JSON Format',
    icon:   'JSON',
    title:  'JSON Formatter / Validator',
    desc:   'JSON 데이터를 자동 포매팅하고 구문 오류를 감지합니다. 들여쓰기 설정, 미니파이, 문자열 이스케이프 변환을 지원합니다.',
    tags:   ['Format', 'Minify', 'Validate', 'Syntax Highlight'],
    footer: 'JSON → Prettify · Minify · Validate',
  },
  {
    href:   'url-encoder.html',
    label:  'URL Encode',
    icon:   'URL',
    title:  'URL Encoder / Decoder',
    desc:   'URL 인코딩·디코딩과 쿼리 파라미터 분석을 지원합니다. encodeURIComponent / encodeURI 모드 선택, 파라미터 파싱 및 JSON 복사 지원.',
    tags:   ['Encode', 'Decode', 'Query Params', 'Parse'],
    footer: 'URL → Encode · Decode · Parse',
  },
  {
    href:   'sql-formatter.html',
    label:  'SQL Format',
    icon:   'FMT',
    title:  'SQL Formatter + Lint',
    desc:   'SQL 구문을 자동 정렬하고 위험 패턴을 빠르게 점검합니다. DELETE/UPDATE without WHERE, SELECT *, DROP/TRUNCATE TABLE 경고를 제공합니다.',
    tags:   ['Format', 'Lint', 'MySQL', 'PostgreSQL', 'Oracle'],
    footer: 'SQL → Format · Quick Safety Lint',
  },
  {
    href:   'cron-builder.html',
    label:  'Cron Builder',
    icon:   'CRON',
    title:  'Cron Builder & Humanize',
    desc:   'Linux 5-field cron 식을 빠르게 생성하고 자연어 해석을 제공합니다. 자주 쓰는 프리셋(매 5분, 평일 9시 등)과 복사 버튼 지원.',
    tags:   ['Cron', 'Schedule', 'Humanize', 'Preset'],
    footer: 'Cron → Build · Explain',
  },
  {
    href:   'mock-data-generator.html',
    label:  'Mock Data',
    icon:   'MOCK',
    title:  'Mock Data Generator',
    desc:   '컬럼 스키마를 기반으로 테스트 데이터를 생성합니다. CSV/JSON/SQL INSERT 출력, seed 기반 재현 가능한 랜덤 데이터 지원.',
    tags:   ['CSV', 'JSON', 'SQL INSERT', 'Seeded Random'],
    footer: 'Schema → Mock Data',
  },
];
